$(document).ready(function(){
    $('.owl-carousel').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        items:4,
        loop:true,
        margin:1,
        autoplay:true,
        autoplayTimeout:5000,
        animateOut: 'fadeOut',
        autoplayHoverPause:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:1
            },
            1000:{
                items:1
            }
        }
    })
  });